// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6OPImvuVpbwrJY9RJ8ewB-fSHgfHbJk4',
    appId: '1:682796724612:web:4e4dd135b9640671feadd1',
    messagingSenderId: '682796724612',
    projectId: 'sns-login-da084',
    authDomain: 'sns-login-da084.firebaseapp.com',
    storageBucket: 'sns-login-da084.appspot.com',
    measurementId: 'G-4TVZ77WY58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGqNE3D5qeEVLkGObQeRJN__pExO6AsQ',
    appId: '1:682796724612:android:54282a3c9186d7affeadd1',
    messagingSenderId: '682796724612',
    projectId: 'sns-login-da084',
    storageBucket: 'sns-login-da084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsx80WDE6eLTM5_OqPpBTAtmHfPRUNWec',
    appId: '1:682796724612:ios:08b5c0ab0a933f5dfeadd1',
    messagingSenderId: '682796724612',
    projectId: 'sns-login-da084',
    storageBucket: 'sns-login-da084.appspot.com',
    androidClientId: '682796724612-cjprbn8ikocv0d180ja32jg2bre2dnpm.apps.googleusercontent.com',
    iosClientId: '682796724612-nhfch0oep8ljpnmos0n8h6l03tq2gu45.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsx80WDE6eLTM5_OqPpBTAtmHfPRUNWec',
    appId: '1:682796724612:ios:b25c1502b00b2e66feadd1',
    messagingSenderId: '682796724612',
    projectId: 'sns-login-da084',
    storageBucket: 'sns-login-da084.appspot.com',
    androidClientId: '682796724612-cjprbn8ikocv0d180ja32jg2bre2dnpm.apps.googleusercontent.com',
    iosClientId: '682796724612-0bmbkvujubq124p9i0iqb8a5e4nmmkc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileapp.RunnerTests',
  );
}
